variable "aws_region" {}
variable "name" {}
variable "vpc_cidr" {}
variable "pubsub_cidr" {}
variable "prisub1_cidr" {}
variable "prisub2_cidr" {}
variable "availability_zone" {}
variable "availability_zone2" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "tags" {}
variable "cluster_name" {}
variable "cluster_version" {}
